info :
  name : ประมวล ฉายเดี่ยว
  description : บอทอะไรก็ไม่รู้
  std : PramualDev
  token : ?PramualTokenDev
  command_prefix : ">>"
  timezone : Asia/Bangkok
  lang : th
  log_ch : 530055377249894421
  err_ch : 568682030817345556
  theme : 0xff7f00
  owner :
      - 269418798975680513 # gongpha#0238       DEVELOPER
      - 338475895285088257 # gongpha#0394       DEVELOPER'S SMURF
      - 357099320069062666 # Kengkat1#4558      TESTER
      - 524907194852966410 # Kengkat2#1787      TESTER'S SMURF
      - 359621664641908736 # Monochrome#0378    TESTER
cogs :
  - cogs.Info
  - cogs.Nuke
  - cogs.MagickBomb
  - cogs.Karaoke
