info :
  name : Pai
  description : |-
    บอทหน้าแมวของ gongpha
    `2a2569300067`
  description_long : ""

  std : PramualPai
  token : ?PramualTokenPai
  command_prefix : "_"
  timezone : Asia/Bangkok
  lang : th
  theme :
      - 0xff7f00
      - 0x007fff
  owner :
      - 269418798975680513 # gongpha#0238       DEVELOPER
      - 338475895285088257 # gongpha#0394       DEVELOPER'S SMURF
      - 357099320069062666 # Kengkat1#4558      TESTER
      - 524907194852966410 # Kengkat2#1787      TESTER'S SMURF
      - 359621664641908736 # Monochrome#0378    TESTER
      - 359616528041246723 # Unallocated#5609	TESTER
  mysql : True
  database_host : ?PramualDatabaseHost
  database_username : ?PramualDatabaseUsername
  database_password : ?PramualDatabasePassword
  database_database : ?PramualDatabaseDatabase
  game_default : OwO
  game_static : ?PramualPaiGame
  where : # leave it empty
channels :
    log   : 530055377249894421
    error : 568682030817345556
    query : 585420046877065216
    guild : 584348191365922828
cogs :
  - cogs.Info
  - cogs.Image
  - cogs.Karaoke
  - cogs.Nuke
  - cogs.MagickBomb
  - cogs.Request
  - cogs.Thai
  - cogs.ImageGenerate
  - cogs.Experimental
auth :
  imgur :
      refresh_token : d434e83984e3e9463989ad236e9d9739ba5785ce
      client_id : f9cbc3a2e673e10
      client_secret : 1c81750ec9b0193949a16ed4db1ea44a25279257
