name : Pai
description :
description_long :
token : ?PramualTokenKoync
command_prefix : "_"
default_timezone : Asia/Bangkok
default_language : th
theme :
    - 0xff7f00
    - 0x007fff
owners :
    - 269418798975680513 # gongpha#0238       DEVELOPER
    - 338475895285088257 # gongpha#0394       DEVELOPER'S SMURF
    - 357099320069062666 # Kengkat1#4558      TESTER
    - 524907194852966410 # Kengkat2#1787      TESTER'S SMURF
    - 359621664641908736 # Monochrome#0378    TESTER
    - 359616528041246723 # Unallocated#5609   TESTER
mysql : True
mysql_hostname : ?PramualDatabaseHost
mysql_username : ?PramualDatabaseUsername
mysql_password : ?PramualDatabasePassword
mysql_database : ?PramualDatabaseDatabase
game_default : OwO
game_static : ?PramualPaiGame
cogs :
  - cogs.Info
  - cogs.Image
  - cogs.Karaoke
  - cogs.Nuke
  - cogs.MagickBomb
  - cogs.Request
  - cogs.Thai
  - cogs.ImageGenerate
  - cogs.Experimental
interface : ?PramualInterface
